In [1]:
#loading the library with the iris dataset
from sklearn.datasets import load_iris

#loading random forest classifier library
from sklearn.ensemble import RandomForestClassifier

#loading pandas
import pandas as pd

#loading numpy
import numpy as np
np.random.seed(0)

In [3]:
#creating object called iris with iris dataset
iris = load_iris()

#creating dataframe with four feature variables
df = pd.DataFrame(iris.data, columns=iris.feature_names)

#viewing top 5 rows
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2

In [4]:
#adding new cloum for species name
df['species'] = pd.Categorical.from_codes(iris.target,iris.target_names)

#viewing top 5 rows
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

  species  
0  setosa  
1  setosa  
2  setosa  
3  setosa  
4  setosa

In [5]:
#craeting test and train data
df['is_train']=np.random.uniform(0,1,len(df)) <=.75

#viewing top 5 rows
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

  species  is_train  
0  setosa      True  
1  setosa      True  
2  setosa      True  
3  setosa      True  
4  setosa      True

In [7]:
#craeting dataframe with test rows  and trainning rows
train,test =df[df['is_train']==True],df[df['is_train']==False]

#show the number of observations for the test and trainning dataframe
print("Number of obervation in training data:",len(train))
print("Number of obervation in test data:",len(test))

Number of obervation in training data: 118
Number of obervation in test data: 32


In [9]:
#creating list of feature column's names
features = df.columns[:4]

#view features
features

Index(['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)',
       'petal width (cm)'],
      dtype='object')

In [11]:
#converting each species name into digits
y = pd.factorize(train['species'])[0]

#viewing target
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2], dtype=int64)

In [16]:
#craeting random forest classifier
clf = RandomForestClassifier(n_jobs=2,random_state=0,n_estimators=10)

#taring the classifier
clf.fit(train[features],y)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
                       max_depth=None, max_features='auto', max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=2,
                       oob_score=False, random_state=0, verbose=0,
                       warm_start=False)

In [17]:
#applying the trained  classifier to the test
clf.predict(test[features])

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 2, 2, 1, 1, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2], dtype=int64)

In [20]:
#viewing the predicted probabilities of the first 10 observation
clf.predict_proba(test[features])[10:20]

array([[1. , 0. , 0. ],
       [1. , 0. , 0. ],
       [1. , 0. , 0. ],
       [0. , 0.5, 0.5],
       [0. , 1. , 0. ],
       [0. , 0.9, 0.1],
       [0. , 0.2, 0.8],
       [0. , 0.3, 0.7],
       [0. , 1. , 0. ],
       [0. , 0.8, 0.2]])

In [23]:
#Mapping names for the plants for each predicted plant class
preds = iris.target_names[clf.predict(test[features])]

#view the predicted  species for the first five observation
preds[0:5]

array(['setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'versicolor', 'versicolor', 'versicolor', 'virginica',
       'virginica', 'versicolor', 'versicolor', 'virginica', 'virginica',
       'virginica', 'virginica', 'virginica'], dtype='<U10')

In [24]:
#view the actual species for the first five observations
test['species'].head()

7     setosa
8     setosa
10    setosa
13    setosa
17    setosa
Name: species, dtype: category
Categories (3, object): [setosa, versicolor, virginica]

In [25]:
#crating confusion matrix
pd.crosstab(test['species'],preds,rownames=['Actual species'],colnames=['predicted Species'])

predicted Species  setosa  versicolor  virginica
Actual species                                  
setosa                 13           0          0
versicolor              0           5          2
virginica               0           0         12

In [27]:
#run model on actual data
preds = iris.target_names[clf.predict([[5.0,3.6,1.4,2.0],[5.0,3.6,1.4,2.0]])]
preds

array(['versicolor', 'versicolor'], dtype='<U10')